services:
  postgres:
    image: postgres:17
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
