import { ClerkProvider } from '@/services/clerk/components/ClerkProvider'
import { UploadThingSSR } from '@/services/uploadthing/components/UploadThingSSR'
import '@mdxeditor/editor/style.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html
				lang='en'
				className={`${geistSans.variable} ${geistMono.variable} h-full antialiased font-sans `}
				suppressHydrationWarning
			>
				<body className='min-h-full flex flex-col'>
					{children}
					<Toaster />
					<UploadThingSSR />
				</body>
			</html>
		</ClerkProvider>
	)
}
